name: Deploy Orvuex AI to Vercel (Fast Mode)

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # Ta machine de guerre (4 vCPUs / 16 Go de RAM)

    steps:
      # 1. Récupération de ton code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Configuration de Flutter avec le système de Cache activé
      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 3. Installation des packages de ton projet
      - name: Installer les dépendances
        run: |
          cd orvuex_flutter
          flutter pub get

      # 4. Compilation Flutter Web en mode ultra-rapide
      # Le --base-href "/" permet d'avoir des liens propres sur Vercel
      - name: Compilation Flutter Web
        run: |
          cd orvuex_flutter
          flutter build web --base-href "/" --release

      # 5. Parachutage direct du résultat (build/web) chez Vercel
      - name: Déploiement Direct sur Vercel
        uses: amondnet/vercel-deploy@v6
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' # On envoie directement sur le lien de production public
          working-directory: ./orvuex_flutter/build/web # On envoie UNIQUEMENT les fichiers web finaux
